# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
# - {name: 'Interesting Facts',  url: 'facts'}
- {name: 'Knowledge', url: 'knowledge'}
- {name: 'Cinema',       url: 'cinema'}
# - {name: 'Documentation',      url: 'documentation'}
- {name: 'About',              url: 'about'}
# - {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link:   'https://www.facebook.com/tqgminh'}
- {icon: 'instagram', link:  'https://instagram.com/moviefromme'}
- {icon: 'twitter', link:    'https://twitter.com/tqgminh'}
- {icon: 'linkedin', link:  'https://www.linkedin.com/in/tqgminh/'}
- {icon: 'envelope', link:   'mailto:quangminhtran22@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newest'
  previous_page: 'Oldest'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
